### ISSUE TITLE
Error while importing frame dump files

### ISSUE THREAD

**Issue by hewiofhiowa** [leotorrez/XXMITools#10]
I've been trying to import models from a 3dmigoto frame dump, but I keep getting this error
`Python: Traceback (most recent call last):
File "C:\Users\(user)\AppData\Roaming\Blender line 294, in execute
import_3dmigoto(self, context, paths, * *keywords)
File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\XXMITools\migoto\datahandling.py", line 1316, in import_3dmigoto
obj.append(import_3dmigoto_vb_ib(operator, context, [p], **kwargs))
File
File
File
Foundation\Blender\4.1\scripts\addons\XXMITools\migoto\datahandling.py", line 1334, in import_3dmigoto_vb_ib
vb, ib, name, pose_path = load_3dmigoto_mesh(operator, paths)
line 953, in load_3dmigoto_mesh
ib = IndexBuffer(open(ib_paths[0], 'r'))
"C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\XXMITools\migoto\datahandling.py",
line 770, in —init—
self.parse_ib_txt(args[O], load_indices)
File "C:\Users\(user)\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\XXMITools\migoto\datahandling.py", line 81 0, in parse_ib_txt
assert(len(self.faces) * self.indices_per_face + self.extra_indices self.index_count)
AssertionError`

**Comment by TerminalAide0017** [comment]
This may be unrelated, but the plugin has never been validated as working on blender 4.1, only on 3.6 and 4
2. Though I imagine there is some kind of issue with the data in the framedump you are attempting to import.

**Comment by leotorrez** [comment]
alternatively you can try "load .buf files" assuming the .txt files have issues

![image](https://github.com/user-attachments/assets/a7c6e561-1e84-4ea6-9d1f-b9f0bebd9aba)

**Comment by leotorrez** [comment]
stale issue. If you are still experiencing the issue feel free to reopen this issue
