### ISSUE TITLE
error when importing assets

### ISSUE THREAD

**Issue by that5515** [leotorrez/XXMITools#20]
im new to blender so im not sure whats the problem, when i try to import assets i get this error, i made sure i downloaded blender 4.2, xxmi tools v1.4.1, the assets are from leotorrez [ZZ-Model-Importer-Assets].
-----------------------------------------------

Python: Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XXMITools\migoto\operators.py", line 295, in execute
    paths = self.get_vb_ib_paths()
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\XXMITools\migoto\operators.py", line 272, in get_vb_ib_paths
    name = os.path.basename(vb_paths[0][0])
                            ~~~~~~~~^^^
IndexError: list index out of range

**Comment by leotorrez** [comment]
which asset tho-

**Comment by that5515** [comment]
Tried Characters assets (PlayerCharacterData), clicked import > (3dmigoto frame analysis dump), after choosing the text files and clicking import i get this error.

What i have tried before coming here:

I tried different characters, like miyabi who was a new asset you added, soukaku, piper.

tried a previous versions of blender after that (4.2, 4.0, 3.6), tried a previous version of xxmi tools after that still failed.
 
tried turning off other add-ons said maybe one of them is interfering, it won't import just immediately error.

**Comment by leotorrez** [comment]
sounds like it should be importing just fine. If you have a discord i recommend going to the server to troubleshoot this faster. discord.gg/agmg

otherswise the issue seems to be caused due to a wrong name on your dump folder

**Comment by CazzoPMX** [comment]
I got the same issue now, and found out (at least for me) it is related to `dirname` containing `[ ]`, which seems to cause issues with glob, which then fails to find any files.

After I replaced (in `get_vb_ib_paths`)
```
dirname = os.path.dirname(self.filepath)
```
with
```
from glob import escape as glob_escape
dirname = glob_escape(os.path.dirname(self.filepath))
```
everything worked fine

**Comment by that5515** [comment]
Thank you both.
